server:
  port: 12010
spring:
  application:
    name: zuul-server
  profiles:
    active: pro #对应的是某个(3种)环境的配置文件
eureka:
  client:
    service-url:
      defaultZone: http://hyzg:123456@127.0.0.1:11010/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点,默认是info和health
  endpoint:
    health:
      show-details: always #默认是never

text:
  myname: zhangquan