server:
  port: 8762
spring:
  application:
    name: hy-goods
  datasource:
      url: jdbc:mysql://10.11.60.21:3306/hchina
      username: root
      password: root
      hikari:
        maximum-pool-size: 30
        minimum-idle: 10
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://hyzg:123456@localhost:11010/eureka/
#actuator设置
management:
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有端点,默认是info和health
  endpoint:
    health:
      show-details: always #默认是never