server:
  port: 11010
spring:
  application:
    name: eureka-server
  security:
    user:
      name: hyzg
      password: 123456
eureka:
  client:
    #两个值搭建eureka集群时开启
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: true # 关闭自我保护
    eviction-interval-timer-in-ms: 5000 # 每隔 5 秒进行一次服务列表清理
  instance:
    hostname: localhost